Traceback (most recent call last):
  File "/home/jfhlewyee/Software/anaconda3/envs/book/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/jfhlewyee/Software/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 1077, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jfhlewyee/Software/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/jfhlewyee/Software/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/jfhlewyee/Software/anaconda3/envs/book/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/jfhlewyee/Software/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 526, in async_execute
    await self.async_execute_cell(
  File "/home/jfhlewyee/Software/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 822, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/jfhlewyee/Software/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 730, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
benzene = psi4.geometry("""
0 1
C 0.0000 1.3970 0.0000
C 1.2098 0.6985 0.0000
C 1.2098 -0.6985 0.0000
C 0.0000 -1.3970 0.0000
C -1.2098 -0.6985 0.0000
C -1.2098 0.6985 0.0000
H 0.0000 2.4810 0.0000
H 2.1486 1.2405 0.0000
H 2.1486 -1.2405 0.0000
H 0.0000 -2.4810 0.0000
H -2.1486 -1.2405 0.0000
H -2.1486 1.2405 0.0000
units angstrom
""")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-3f2a2dd0e801>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m benzene = psi4.geometry("""
[0m[1;32m      2[0m [0;36m0[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mC[0m [0;36m0.0000[0m [0;36m1.3970[0m [0;36m0.0000[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mC[0m [0;36m1.2098[0m [0;36m0.6985[0m [0;36m0.0000[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mC[0m [0;36m1.2098[0m [0;34m-[0m[0;36m0.6985[0m [0;36m0.0000[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'psi4' is not defined
NameError: name 'psi4' is not defined

