Traceback (most recent call last):
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Grafica

from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import matplotlib.pyplot as plt

#Numero cuantico
ml=1

#Coordenadas polares
phi = np.linspace(0, 2 * np.pi, 100)
r=1.0
psi_r = np.sqrt(1/(2*np.pi))*np.cos(ml*phi)
psi_i = np.sqrt(1/(2*np.pi))*np.sin(ml*phi)

#Grafica de la funcion de onda
fig = plt.figure()
ax = fig.gca(projection='3d')
x = r * np.sin(phi)
y = r * np.cos(phi)
ax.plot(x, y, 0, color='k') #Eje de la grafica
ax.plot(x, y, psi_r, label='psi-R')
ax.plot(x, y, psi_i, label='psi-I')
ax.legend()
plt.show()

#Grafica del cuadrado de la funcion de onda
fig = plt.figure()
ax = fig.gca(projection='3d')
x = r * np.sin(phi)
y = r * np.cos(phi)
ax.plot(x, y, 0, color='k') #Eje de la grafica
ax.plot(x, y, ((psi_r+1J*psi_i)*(psi_r-1J*psi_i)).real, label='$psi^2$')
ax.legend()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# Grafica[39;00m
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmpl_toolkits[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmplot3d[39;00m [38;5;28;01mimport[39;00m Axes3D
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m

[0;31mModuleNotFoundError[0m: No module named 'mpl_toolkits'
ModuleNotFoundError: No module named 'mpl_toolkits'

