Traceback (most recent call last):
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
mp2 = pyscf.mp.MP2(mol)
E_corr = mp2.kernel()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [27][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m mp2 [38;5;241m=[39m [43mpyscf[49m[38;5;241;43m.[39;49m[43mmp[49m[38;5;241m.[39mMP2(mol)
[1;32m      2[0m E_corr [38;5;241m=[39m mp2[38;5;241m.[39mkernel()

[0;31mAttributeError[0m: module 'pyscf' has no attribute 'mp'
AttributeError: module 'pyscf' has no attribute 'mp'

